### ISSUE TITLE
A2C_TangyPack & COLOR BARS

### ISSUE THREAD

**Issue by JDW1** [rowokii/A2C_TangyPack#6]
Rob,

I sent you an email yesterday, but it might have ended up on your SPAM filter.  I know it's out of place to post it here, but I have no other way to reach you.

I watched your Kansas Fest 2024 presentation about the Apple IIc Tangy Pack, and I noticed you used some interesting COLOR BARS at 12:27 in this video:

https://youtu.be/Xh7fbzj6SgQ?si=3Ifv300H1Nu9JLuq&t=747

Would you mind sharing a download URL for the disk image that generates those color bars?

Thanks!

**Comment by rowokii** [comment]
Hi James,

It's just a few basic programs I wrote when I was testing to display different color images.   Dos 3.3 dsk image is here:

[https://github.com/rowokii/A2C_TangyPack/blob/main/Software/A2_Graphics.dsk](https://github.com/rowokii/A2C_TangyPack/blob/main/Software/A2_Graphics.dsk)

Cheers!

**Comment by JDW1** [comment]
Hi Rob,

I wish to humbly thank you for your kindness in sharing the *.dsk image.  

I tested it just now in [Virtual II](https://www.virtualii.com) and found a bug regarding menu choices C & E, both of which pertain to **HGR**:

###  CHOICE "C":
![Menu-HGRBAR](https://github.com/user-attachments/assets/e6d29a4e-bf43-43b5-a8c5-c450fdc1fc41)

### Emulated IIc:
![HGRBAR-IIcError](https://github.com/user-attachments/assets/8445ecf9-2f37-413d-8a87-8d20728ed383)

### Emulated IIe:
![HGRBAR-IIeError](https://github.com/user-attachments/assets/0e90a220-b540-4f81-90c1-686ba5a71827)

### CHOICE "E":
![Menu-RNDHGR](https://github.com/user-attachments/assets/e6f2d656-8ea9-404d-b830-63653b30cc67)

### No "Illegal QTY" error, but I suspect this display is not what you intended:
![RNDHGR_IIeError](https://github.com/user-attachments/assets/2fbd55a2-8b76-427c-8d50-bb534ba80907)

**Comment by rowokii** [comment]
Actually, I misnamed those files.  It's not running HGR modes but Double Low Res (DGR?) modes on those.  

It works fine on an actual Apple IIc/IIc+.  I get the same errors on Laser 128 and Applewin emulating enhanced IIe.

Quick google search shows this post:
https://retrocomputing.stackexchange.com/questions/384/what-are-the-differences-between-the-versions-of-applesoft-basic

Under Apple IIc/ IIc Plus
    "The lo-res graphics commands (GR, HLIN, VLIN, PLOT, and SCRN) work with double lo-res"

So, the syntax error is because HLIN value of 79 is not valid in the previous version of Applesoft.  I guess most emulators emulates IIe, so this doesn't work...

IIc gets no love!  😀

**Comment by JDW1** [comment]
Thanks, I plan to test it on my real IIc (not plus) this evening after work.  I appreciate the info!

**Comment by JDW1** [comment]
Rob, I made this video and shared it on FaceBook in the Apple II group so other people will more easily be able to find it.  

https://youtu.be/cFw3JKDPhRs?si=sV8AN5Iqma69Ogw5

Thanks again for kindly making it available!
